"""Generate the independent Perc Generator adaptation (hidden Gen code unavailable)."""


NOTES = [24, 24, 42, 42, 42, 42, 42, 42, 42, 42, 63, 63, 63, 63, 63, 63]
PROBS = [.2, .08, .4, .12, .02, .3, .08, .18, .4, .06, .22, .1, .35, .08, .15, .28]


def build_percussion(Patch):
    p = Patch('Perc clock: actual audio-clock edges -> 16 steps -> sequence / transition-selected pitches.')
    beats = p.obj(r'r~ \$1-beats'); phase = p.obj('wrap~')
    edge = p.obj('fexpr~ $x1[0] < $x1[-1]'); threshold = p.obj('threshold~ 0.5 0 0.1 0')
    p.chain(beats, phase, edge, threshold)
    run = p.obj(r'r \$1-run'); gate = p.obj('spigot 0'); p.chain(threshold, gate); p.link(run, gate, inp=1)
    order = p.obj('t b b b'); p.chain(gate, order)
    count = p.obj('f 0'); advance = p.obj('+ 1'); wrap = p.obj('% 16'); step = p.obj('t f f f')
    p.link(order, count, out=2); p.chain(count, step)
    p.link(step, advance, out=2); p.chain(advance, wrap); p.link(wrap, count, inp=1)
    p.link(step, p.obj(r's \$1-perc-step'), out=1)
    read = p.obj(r'tabread \$1-perc-notes'); p.chain(step, read, p.obj(r's \$1-perc-note0'))
    markov = p.obj(r'zp-perc-markov \$1'); p.link(order, markov, out=1)
    p.chain(markov, p.obj(r's \$1-perc-note1'))
    p.link(order, p.obj(r's \$1-perc-tick'))
    reset = p.obj(r'r \$1-reset'); zero = p.msg('0'); p.chain(reset, zero); p.link(zero, count, inp=1)
    p.write('zp-perc-clock')

    # Weighted first-order transitions from the current editable 16-note sequence.
    # Each occurrence contributes one successor, preserving repeated-note weights.
    p = Patch('Independent anal/prob replacement: select a successor of the previous note from the sequence.')
    inlet = p.obj('inlet'); order = p.obj('t b b b'); p.chain(inlet, order)
    table = p.obj(r'array define \$0-candidates 16')
    clear = p.msg('0'); loopcount = p.msg('16'); until = p.obj('until')
    i = p.obj('f 0'); inc = p.obj('+ 1'); ii = p.obj('t f f')
    candidates = p.obj('f 0'); total = p.obj('f 0')
    p.link(order, clear, out=2); p.link(clear, i, inp=1); p.link(clear, candidates, inp=1); p.link(clear, total, inp=1)
    p.link(order, loopcount, out=1); p.chain(loopcount, until, i, ii)
    p.link(ii, inc, out=1); p.link(inc, i, inp=1)
    split = p.obj('t f f'); p.chain(ii, split)
    nxt = p.obj('+ 1'); wrap = p.obj('% 16'); nextnote = p.obj(r'tabread \$1-perc-notes'); store = p.obj('f 24')
    p.link(split, nxt, out=1); p.chain(nxt, wrap, nextnote); p.link(nextnote, store, inp=1)
    current = p.obj(r'tabread \$1-perc-notes'); equal = p.obj('== 24'); select = p.obj('sel 1')
    p.chain(split, current, equal, select)
    append = p.obj('t b b'); indexes = p.obj('t f f'); plus = p.obj('+ 1'); write = p.obj(r'tabwrite \$0-candidates')
    p.chain(select, append); p.link(append, candidates, out=1); p.chain(candidates, indexes)
    p.link(indexes, write, out=1, inp=1); p.chain(indexes, plus)
    p.link(plus, candidates, inp=1); p.link(plus, total, inp=1); p.chain(append, store, write)
    p.chain(order, total)
    choose = p.obj('moses 1'); randomorder = p.obj('t b f'); rand = p.obj('random 16'); result = p.obj(r'tabread \$0-candidates')
    fallback = p.obj('f 24'); seq = p.obj(r'r \$1-perc-note0'); p.link(seq, fallback, inp=1)
    bang = p.obj('t b')
    p.chain(total, choose); p.chain(choose, bang, fallback); p.link(choose, randomorder, out=1)
    p.link(randomorder, rand, out=1, inp=1); p.chain(randomorder, rand, result)
    output = p.obj('t f f'); outlet = p.obj('outlet'); p.chain(result, output, outlet)
    p.chain(fallback, output); p.link(output, equal, out=1, inp=1)
    reset = p.obj(r'r \$1-reset'); initial = p.msg('24'); p.chain(reset, initial); p.link(initial, equal, inp=1)
    seed = p.obj(r'r \$1-seed'); seedmsg = p.msg(r'seed \$1'); p.chain(seed, seedmsg, rand)
    p.write('zp-perc-markov')

    p = Patch('One of 32 percussion voices. FM body + filtered-noise transient = inferred Gen replacement.')
    p.text('Arguments: clone voice index / namespace. Banks 0..15 sequence and 16..31 transition pitch.',25,760)
    tick = p.obj(r'r \$2-perc-tick'); trig = p.obj('t b b')
    step = p.obj(r'r \$2-perc-step'); index = p.obj(r'expr (int($f1)+\$1)%16')
    prob = p.obj(r'tabread \$2-perc-probs'); density = p.obj(r'r \$2-perc-density'); scale = p.obj('* 1')
    p.chain(step,index,prob,scale); p.link(density,scale,inp=1)
    p.chain(tick,trig)
    random = p.obj('random 1000000'); unit = p.obj('/ 1000000'); less = p.obj('< 0.2'); hit = p.obj('sel 1')
    p.link(trig,random); p.chain(random,unit,less,hit); p.link(scale,less,inp=1)
    seed = p.obj(r'r \$2-seed'); offset = p.obj(r'expr int(abs($f1))+\$1*7919+73'); seedmsg = p.msg(r'seed \$1')
    p.chain(seed,offset,seedmsg,random)
    # Two equal 16-channel banks, as visible at mc.combine~ in the video.
    a = p.obj(r'r \$2-perc-note0'); b = p.obj(r'r \$2-perc-note1')
    ga = p.obj('spigot'); gb = p.obj('spigot'); lb = p.obj('loadbang')
    isA = p.obj(r'expr \$1<16'); isB = p.obj(r'expr \$1>=16')
    p.chain(lb,isA); p.link(lb,isB); p.link(isA,ga,inp=1); p.link(isB,gb,inp=1)
    p.chain(a,ga); p.chain(b,gb)
    pitch = p.obj('f 45'); p.link(ga,pitch,inp=1); p.link(gb,pitch,inp=1)
    onset = p.obj('t b b b'); p.chain(hit,onset); p.link(onset,pitch,out=2)
    root = p.obj(r'r \$2-root'); transpose = p.obj('- 60'); add = p.obj('+ 0'); p.chain(root,transpose); p.link(transpose,add,inp=1)
    p.chain(pitch,add)
    spread = p.obj(r'expr ((\$1%16)-7.5)*0.13+$f1'); hz = p.obj('mtof'); p.chain(add,spread,hz)
    base = p.obj('sig~ 100'); p.chain(hz,base)
    ratio = p.obj(r'*~ 1.41421356'); fmOsc = p.obj('osc~'); p.chain(base,ratio,fmOsc)
    decay = p.obj(r'r \$2-perc-decay'); duration = p.obj('f 160'); p.link(decay,duration,inp=1)
    p.link(onset,duration,out=1)
    varied = p.obj(r'expr $f1*(0.5+(\$1%8)/10)'); envelope = p.msg(r'0 0 \, 1 1 \, 0 \$1 1'); env = p.obj('vline~')
    p.chain(duration,varied,envelope,env)
    squared = p.obj('*~'); p.link(env,squared); p.link(env,squared,inp=1)
    amount = p.signal(r'\$2-perc-color'); modulation = p.obj('expr~ $v1*$v2*$v3*$v4*3')
    p.link(fmOsc,modulation); p.link(base,modulation,inp=1); p.link(squared,modulation,inp=2); p.link(amount,modulation,inp=3)
    frequency = p.obj('+~'); p.link(base,frequency); p.link(modulation,frequency,inp=1)
    osc = p.obj('osc~'); p.chain(frequency,osc)
    noise = p.obj('noise~'); high = p.obj('hip~ 1800'); p.chain(noise,high)
    noiselevel = p.obj(r'*~ 0.15'); p.chain(high,noiselevel)
    mix = p.obj('+~'); p.link(osc,mix); p.link(noiselevel,mix,inp=1)
    volume = p.obj('*~'); p.link(mix,volume); p.link(squared,volume,inp=1)
    audio = p.obj('*~ 0.045'); p.chain(volume,audio)
    # Alternate voices across the stereo downmix; mono sum is formed in the engine.
    for side in range(2):
        pan=p.obj('*~ '+str(1 if side==0 else 0))
        angle=p.obj(r'expr '+('cos' if side==0 else 'sin')+r'((\$1%16)/15*1.5707963)')
        p.link(lb,angle); p.link(angle,pan,inp=1); p.link(audio,pan)
        p.chain(pan,p.obj('outlet~',25+side*190,810))
    monitor = p.obj('snapshot~'); ui = p.obj(r'r \$2-ui-tick'); meter = p.obj(r'tabwrite \$2-perc-voices'); vid=p.obj(r'f \$1')
    p.link(squared,monitor); p.link(ui,monitor); p.chain(monitor,meter); p.chain(lb,vid); p.link(vid,meter,inp=1)
    p.write('zp-perc-voice')

    p = Patch('Perc Generator adaptation: 32 voices / 520 and 260 Hz crossovers / 500 ms stereo delay.')
    p.obj(r'zp-perc-clock \$1')
    voices = p.obj(r'clone zp-perc-voice 32 \$1'); mono = p.obj('+~')
    p.link(voices,mono); p.link(voices,mono,out=1,inp=1)
    low = p.obj('zp-cross 520'); p.chain(mono,low)
    lowgain = p.obj('*~ 1.4'); p.chain(low,lowgain)
    outputs=[]
    delay=p.signal(r'\$1-perc-delay',120); delayclip=p.obj('clip~ 5 1900'); p.chain(delay,delayclip)
    beats=p.obj(r'r~ \$1-beats')
    feedback=p.signal(r'\$1-perc-feedback',120)
    for side in range(2):
        high=p.obj('zp-cross 260'); p.link(voices,high,out=side)
        highgain=p.obj('*~ 0.5'); p.link(high,highgain,out=1)
        dry=p.obj('+~'); p.link(lowgain,dry); p.link(highgain,dry,inp=1)
        shape=p.obj('expr~ tanh($v1*1.3)'); p.chain(dry,shape)
        # 1/2/4 divisors are visible; exact Gen delay modulation is not.
        modulation=p.obj('expr~ 8*sin(6.2831853*$v1/'+str(2 if side==0 else 4)+')')
        p.chain(beats,modulation)
        time=p.obj('+~'); p.link(delayclip,time); p.link(modulation,time,inp=1)
        bounded=p.obj('clip~ 2 1990'); p.chain(time,bounded)
        rd=p.obj(r'delread4~ \$0-delay'+str(side)); p.chain(bounded,rd)
        fb=p.obj('*~'); p.link(rd,fb); p.link(feedback,fb,inp=1)
        damping=p.obj('lop~ 7000'); p.chain(fb,damping)
        loop=p.obj('+~'); p.link(shape,loop); p.link(damping,loop,inp=1)
        limited=p.obj('expr~ tanh($v1)'); write=p.obj(r'delwrite~ \$0-delay'+str(side)+' 2000'); p.chain(loop,limited,write)
        wet=p.obj('*~ 0.4'); p.chain(rd,wet)
        mixed=p.obj('+~'); p.link(shape,mixed); p.link(wet,mixed,inp=1)
        sat=p.obj('expr~ tanh($v1)'); hp=p.obj('hip~ 20'); p.chain(mixed,sat,hp)
        outputs.append(hp)
    # Explicit x positions ensure outlet 0 really is left, even if layout grows.
    for side,audio in enumerate(outputs): p.chain(audio,p.obj('outlet~',30+side*180,800))
    reset=p.obj(r'r \$1-reset'); clear=p.msg('clear'); p.chain(reset,clear)
    for i,node in enumerate(p.nodes):
        if 'delwrite~' in node: p.link(clear,i)
    p.write('zp-perc')

    p = Patch('PERC / extended controls',1000,390)
    p.text('Uses this instrument clock / transport / master. Open from perc-generator.',25,45)
    for i,(name,lo,hi,label) in enumerate([
            ('perc',0,1,'LEVEL'),('perc-density',0,2,'GATE_SCALE'),
            ('perc-decay',10,1000,'DECAY_ms'),('perc-color',0,1,'FM_COLOR'),
            ('perc-delay',5,1900,'DELAY_ms'),('perc-feedback',0,.75,'FEEDBACK')]):
        x=25+(i%3)*310; y=110+(i//3)*70
        p.obj(f'nbx 8 20 {lo} {hi} 0 0 \\$1-{name}-edit \\$1-{name}-ui {label} 0 -10 0 12 #ffffff #000000 #000000 0 256',x,y)
        p.obj(r'zp-control \$1 '+name,x,y+28)
    p.text('Edit notes and probabilities in the main instrument. Its lower graph shows live envelopes.',25,265)
    p.text('Market mode controls level / density / decay / color / feedback automatically.',25,305)
    p.text('This adaptation synthesizes percussion. No sample loader is visible in the reference.',25,345)
    p.write('zp-perc-panel')
