import {fileURLToPath} from 'node:url';
import {tmpdir} from 'node:os';
const {chromium,webkit}=await import(process.env.AV_PLAYWRIGHT_MODULE||'playwright');
import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
const root=fileURLToPath(new URL('../public/',import.meta.url));
const fixture=`<!doctype html><html><head><link rel="stylesheet" href="/style.css"></head><body><main><aside class="audio-visualizer"><canvas id="audio-dots"></canvas></aside></main><script type="module">
import {createAudioDots,fieldState} from '/audio-dots.js';
let playing=true, level=.75;const analyser={fftSize:2048,frequencyBinCount:1024,context:{state:'running',currentTime:0,sampleRate:48000},getFloatTimeDomainData(a){for(let i=0;i<a.length;i++)a[i]=Math.sin(i*.1)*level*.1;},getByteFrequencyData(a){for(let i=0;i<a.length;i++)a[i]=Math.max(0,Math.sin(i*.03)*180-i*.07)*level;}};
const view=createAudioDots(document.querySelector('canvas'),{getAudio:()=>analyser,getState:()=>({playing})});
const base={fresh:1,decoded:true,raw:{activity:.8,volume:.8,motion:.7},music:{intensity:.9,tempo:132,changePct:24.73},dataSignals:{density:.7},balance:.63,observedVolume:49630,tradeRate:8,observation:{liquidity:852000},audience:{holders:55298,weight:1},context:{pressure:.8,latestCap:8420000,path:Array.from({length:180},(_,i)=>({time:i*60000,close:Math.exp(i*.005+Math.sin(i*.17)*.12+Math.sin(i*.041)*.27),volume:9000+Math.sin(i*.27)*4000}))}};
window.fixture={replay(position,seeking=false){playing=true;view.frame({...base,replay:{source:'candles',volume:12000,price:1+position*.01,at:position*60000}},{playing:true,seed:1917,position,seeking});},seek(position){view.reset();this.replay(position,true);this.replay(position);},event(id){view.event({kind:'swap',id,receivedAt:Date.now(),priceUsd:1.25,usdVolume:24000});},set(type){playing=type!=='paused';level=type==='quiet'?0:.75;let m=structuredClone(base);if(type==='quiet'){m.raw={activity:0,volume:0,motion:0};m.music.intensity=0;m.music.changePct=0;m.dataSignals.density=0;}if(type==='stale')m.fresh=0;view.frame(m,{playing,seed:1917});},model:fieldState(base)};window.fixture.set('busy');
</script></body></html>`;
const server=http.createServer(async(req,res)=>{try{const name=new URL(req.url,'http://local').pathname;const data=name==='/'?fixture:await fs.readFile(path.join(root,name));res.setHeader('Content-Type',name==='/'?'text/html':name.endsWith('.css')?'text/css':'text/javascript');res.end(data);}catch(e){res.statusCode=404;res.end(e.message);}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
let browser;
try{browser=await (process.env.UPIC_WEBKIT?webkit:chromium).launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.waitForFunction(()=>window.fixture);await page.waitForTimeout(150);
const state=()=>page.locator('canvas').evaluate(c=>({...c.dataset,width:c.width,height:c.height}));
const waitFlag=(key,value)=>page.waitForFunction(({key,value})=>document.querySelector('canvas').dataset[key]===String(value),{key,value},{polling:'raf'});
const fieldImage=()=>page.locator('canvas').evaluate(c=>c.toDataURL());
await waitFlag('visible',true);await waitFlag('transitioning',false);const initial=await state();assert.ok(Number(initial.density)>0,'The current observation should establish a persistent score');
await page.evaluate(()=>fixture.event('trade-1'));await waitFlag('transitioning',true);const busy=await state();assert.equal(busy.visible,'true');assert.ok(Number(busy.density)>.4);assert.equal(busy.composition,initial.composition);assert.equal(busy.phase,initial.phase,'New trades should retain the coin’s composition and registration');const inkCoverage=await page.locator('canvas').evaluate(c=>{const data=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let ink=0;for(let i=0;i<data.length;i+=4)if(data[i]<128&&data[i+3]>128)ink++;return ink/(data.length/4);});assert.ok(inkCoverage>.015&&inkCoverage<.3,'An active score should have legible fine marks while retaining its white field');await page.screenshot({path:path.join(tmpdir(),'upic-field-busy.png')});
await waitFlag('transitioning',false);await page.waitForTimeout(250);assert.equal((await state()).visible,'true','The score must remain after the 420ms update blend');await page.evaluate(()=>fixture.event('trade-next'));await waitFlag('transitioning',true);assert.equal((await state()).visible,'true','New observations must blend without a blank gap');await waitFlag('transitioning',false);
await page.evaluate(()=>fixture.event('trade-1'));await page.waitForTimeout(80);assert.equal((await state()).transitioning,'false','A repeated trade must not begin another transition');
await page.evaluate(()=>fixture.event('trade-2'));await waitFlag('transitioning',true);await page.evaluate(()=>fixture.set('paused'));await waitFlag('active',false);await waitFlag('transitioning',false);assert.equal((await state()).visible,'true');const frozen=await page.locator('canvas').evaluate(c=>({image:c.toDataURL(),phase:c.dataset.phase}));await page.waitForTimeout(300);assert.deepEqual(await page.locator('canvas').evaluate(c=>({image:c.toDataURL(),phase:c.dataset.phase})),frozen,'Pause must retain the score and leave its image still');
const retained=await fieldImage();await page.evaluate(()=>fixture.set('quiet'));await page.waitForTimeout(250);const quiet=await state();assert.equal(quiet.visible,'true');assert.equal(quiet.transitioning,'false');assert.ok(Number(quiet.density)>0);assert.equal(await fieldImage(),retained,'A quiet market must retain its last score without motion');await page.screenshot({path:path.join(tmpdir(),'upic-field-quiet.png')});
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>fixture.set('busy'));await page.waitForTimeout(150);const mobile=await page.locator('canvas').evaluate(c=>({width:c.getBoundingClientRect().width,height:c.getBoundingClientRect().height,active:c.dataset.active}));assert.ok(mobile.width>300&&mobile.height>250);assert.equal(mobile.active,'true');const overlay=await page.locator('canvas').evaluate(c=>{const host=c.closest('.audio-visualizer'),style=getComputedStyle(host),pixels=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let transparent=0,ink=0;for(let i=0;i<pixels.length;i+=4){if(pixels[i+3]===0)transparent++;else if(pixels[i]>240&&pixels[i+1]>240&&pixels[i+2]>240)ink++;}return {parent:host.parentElement.tagName,blend:style.mixBlendMode,pointer:style.pointerEvents,caption:host.querySelector('.visualizer-caption')!==null,transparent:transparent/(pixels.length/4),ink};});assert.deepEqual({parent:overlay.parent,blend:overlay.blend,pointer:overlay.pointer,caption:overlay.caption},{parent:'BODY',blend:'difference',pointer:'none',caption:false});assert.ok(overlay.transparent>.5&&overlay.ink>0,'Mobile must retain white marks over a transparent background');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>fixture.event('trade-mobile'));await waitFlag('transitioning',true);await page.screenshot({path:path.join(tmpdir(),'upic-field-mobile.png')});await waitFlag('transitioning',false);
await page.evaluate(()=>fixture.seek(12));await page.waitForTimeout(70);await waitFlag('visible',true);await waitFlag('transitioning',false);assert.ok(Number((await state()).density)>0,'Seeking should establish the selected candle as a visible baseline');
await page.evaluate(()=>fixture.replay(13));await waitFlag('transitioning',true);const replayPhase=(await state()).phase;await waitFlag('transitioning',false);
await page.evaluate(()=>fixture.seek(12));await page.waitForTimeout(70);await waitFlag('visible',true);await waitFlag('transitioning',false);await page.evaluate(()=>fixture.replay(13));await waitFlag('transitioning',true);assert.equal((await state()).phase,replayPhase,'Replaying the same candle must reproduce its event geometry');await waitFlag('transitioning',false);
await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>{fixture.seek(40);fixture.replay(41);});await page.waitForTimeout(70);await waitFlag('visible',true);await waitFlag('transitioning',false);const phase=(await state()).phase,image=await page.locator('canvas').evaluate(c=>c.toDataURL());await page.waitForTimeout(250);const reduced=await state();assert.equal(reduced.phase,phase);assert.ok(Number(reduced.density)>0,'Reduced motion must retain the observed score');assert.equal(reduced.transitioning,'false');assert.equal(await page.locator('canvas').evaluate(c=>c.toDataURL()),image,'Reduced motion should remain still between observations');assert.deepEqual(errors,[]);console.log(JSON.stringify({busy,inkCoverage,quiet,mobile,errors,persistentScore:true,pausedRetained:true,reducedMotion:true},null,2));}finally{await browser?.close();server.close();}
