import {fileURLToPath} from 'node:url';
import {tmpdir} from 'node:os';
const {chromium,webkit}=await import(process.env.AV_PLAYWRIGHT_MODULE||'playwright');
import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
const root=fileURLToPath(new URL('../public/',import.meta.url));
const fixture=`<!doctype html><html><head><link rel="stylesheet" href="/style.css"></head><body><main><aside class="audio-visualizer"><canvas id="audio-dots"></canvas><div class="visualizer-caption"><span>OFFLINE MARKET FIXTURE</span><span>LISTENING</span></div></aside></main><script type="module">
import {createAudioDots,fieldState} from '/audio-dots.js';
let playing=true, level=.75;const analyser={fftSize:2048,frequencyBinCount:1024,context:{state:'running',currentTime:0,sampleRate:48000},getFloatTimeDomainData(a){for(let i=0;i<a.length;i++)a[i]=Math.sin(i*.1)*level*.1;},getByteFrequencyData(a){for(let i=0;i<a.length;i++)a[i]=Math.max(0,Math.sin(i*.03)*180-i*.07)*level;}};
const view=createAudioDots(document.querySelector('canvas'),{getAudio:()=>analyser,getState:()=>({playing})});
const base={fresh:1,decoded:true,raw:{activity:.8,volume:.8,motion:.7},music:{intensity:.9,tempo:132,changePct:24.73},dataSignals:{density:.7},balance:.63,observedVolume:49630,tradeRate:8,observation:{liquidity:852000},audience:{holders:55298,weight:1},context:{pressure:.8,latestCap:8420000,path:Array.from({length:180},(_,i)=>({time:i*60000,close:Math.exp(i*.005+Math.sin(i*.17)*.12+Math.sin(i*.041)*.27),volume:9000+Math.sin(i*.27)*4000}))}};
window.fixture={replay(position){playing=true;view.frame({...base,replay:{source:'candles',volume:12000,at:position*60000}},{playing:true,seed:1917,position});},set(type){playing=type!=='paused';level=type==='quiet'?0:.75;let m=structuredClone(base);if(type==='quiet'){m.raw={activity:0,volume:0,motion:0};m.music.intensity=0;m.music.changePct=0;m.dataSignals.density=0;}if(type==='stale')m.fresh=0;view.frame(m,{playing,seed:1917});},model:fieldState(base)};window.fixture.set('busy');
</script></body></html>`;
const server=http.createServer(async(req,res)=>{try{const name=new URL(req.url,'http://local').pathname;const data=name==='/'?fixture:await fs.readFile(path.join(root,name));res.setHeader('Content-Type',name==='/'?'text/html':name.endsWith('.css')?'text/css':'text/javascript');res.end(data);}catch(e){res.statusCode=404;res.end(e.message);}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
let browser;
try{browser=await (process.env.UPIC_WEBKIT?webkit:chromium).launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.waitForFunction(()=>window.fixture);await page.waitForTimeout(1200);await page.screenshot({path:path.join(tmpdir(),'upic-field-busy.png')});
const busy=await page.locator('canvas').evaluate(c=>({...c.dataset,width:c.width,height:c.height}));assert.ok(Number(busy.density)>.4);await page.evaluate(()=>fixture.set('paused'));await page.waitForTimeout(150);const frozen=await page.locator('canvas').evaluate(c=>({image:c.toDataURL(),phase:c.dataset.phase}));await page.waitForTimeout(300);assert.deepEqual(await page.locator('canvas').evaluate(c=>({image:c.toDataURL(),phase:c.dataset.phase})),frozen,'Paused field must freeze');
await page.evaluate(()=>fixture.set('quiet'));await page.waitForTimeout(1200);const quiet=await page.locator('canvas').evaluate(c=>({...c.dataset}));assert.ok(Number(quiet.density)<.03);await page.screenshot({path:path.join(tmpdir(),'upic-field-quiet.png')});
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>fixture.set('busy'));await page.waitForTimeout(900);const mobile=await page.locator('canvas').evaluate(c=>({width:c.getBoundingClientRect().width,height:c.getBoundingClientRect().height,active:c.dataset.active}));assert.ok(mobile.width>300&&mobile.height>250);assert.equal(mobile.active,'true');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(tmpdir(),'upic-field-mobile.png')});
await page.evaluate(()=>fixture.replay(12.5));await page.waitForTimeout(150);const replayPhase=await page.locator('canvas').getAttribute('data-phase');await page.evaluate(()=>fixture.replay(50));await page.waitForTimeout(150);assert.notEqual(await page.locator('canvas').getAttribute('data-phase'),replayPhase);await page.evaluate(()=>fixture.replay(12.5));await page.waitForTimeout(150);assert.equal(await page.locator('canvas').getAttribute('data-phase'),replayPhase,'Seeking the same historical position must reproduce the visual geometry');
await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(300);const phase=await page.locator('canvas').getAttribute('data-phase');await page.waitForTimeout(500);assert.equal(await page.locator('canvas').getAttribute('data-phase'),phase);assert.deepEqual(errors,[]);console.log(JSON.stringify({busy,quiet,mobile,errors,pausedFrozen:true,reducedMotion:true},null,2));}finally{await browser?.close();server.close();}
