import {fileURLToPath} from 'node:url';
import {tmpdir} from 'node:os';
const {chromium,webkit}=await import(process.env.AV_PLAYWRIGHT_MODULE||'playwright');
import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
const root=fileURLToPath(new URL('../public/',import.meta.url));
const fixture=`<!doctype html><html><head><link rel="stylesheet" href="/style.css"></head><body><main><aside class="audio-visualizer"><canvas id="audio-dots"></canvas><div class="visualizer-caption"><span>OFFLINE MARKET FIXTURE</span><span>LISTENING</span></div></aside></main><script type="module">
import {createAudioDots,fieldState} from '/audio-dots.js';
let playing=true, level=.75;const analyser={fftSize:2048,frequencyBinCount:1024,context:{state:'running',currentTime:0,sampleRate:48000},getFloatTimeDomainData(a){for(let i=0;i<a.length;i++)a[i]=Math.sin(i*.1)*level*.1;},getByteFrequencyData(a){for(let i=0;i<a.length;i++)a[i]=Math.max(0,Math.sin(i*.03)*180-i*.07)*level;}};
const view=createAudioDots(document.querySelector('canvas'),{getAudio:()=>analyser,getState:()=>({playing})});
const base={fresh:1,decoded:true,raw:{activity:.8,volume:.8,motion:.7},music:{intensity:.9,tempo:132,changePct:24.73},dataSignals:{density:.7},balance:.63,observedVolume:49630,tradeRate:8,observation:{liquidity:852000},audience:{holders:55298,weight:1},context:{pressure:.8,latestCap:8420000,path:Array.from({length:180},(_,i)=>({time:i*60000,close:Math.exp(i*.005+Math.sin(i*.17)*.12+Math.sin(i*.041)*.27),volume:9000+Math.sin(i*.27)*4000}))}};
window.fixture={replay(position,seeking=false){playing=true;view.frame({...base,replay:{source:'candles',volume:12000,price:1+position*.01,at:position*60000}},{playing:true,seed:1917,position,seeking});},seek(position){view.reset();this.replay(position,true);this.replay(position);},event(id){view.event({kind:'swap',id,receivedAt:Date.now(),priceUsd:1.25,usdVolume:24000});},set(type){playing=type!=='paused';level=type==='quiet'?0:.75;let m=structuredClone(base);if(type==='quiet'){m.raw={activity:0,volume:0,motion:0};m.music.intensity=0;m.music.changePct=0;m.dataSignals.density=0;}if(type==='stale')m.fresh=0;view.frame(m,{playing,seed:1917});},model:fieldState(base)};window.fixture.set('busy');
</script></body></html>`;
const server=http.createServer(async(req,res)=>{try{const name=new URL(req.url,'http://local').pathname;const data=name==='/'?fixture:await fs.readFile(path.join(root,name));res.setHeader('Content-Type',name==='/'?'text/html':name.endsWith('.css')?'text/css':'text/javascript');res.end(data);}catch(e){res.statusCode=404;res.end(e.message);}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
let browser;
try{browser=await (process.env.UPIC_WEBKIT?webkit:chromium).launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.waitForFunction(()=>window.fixture);await page.waitForTimeout(150);
const state=()=>page.locator('canvas').evaluate(c=>({...c.dataset,width:c.width,height:c.height}));
const waitBurst=value=>page.waitForFunction(value=>document.querySelector('canvas').dataset.burst===String(value),value,{polling:'raf'});
assert.equal((await state()).burst,'false','Rolling activity alone must not draw an event');
await page.evaluate(()=>fixture.event('trade-1'));await waitBurst(true);const busy=await state();assert.ok(Number(busy.density)>.4);await page.screenshot({path:path.join(tmpdir(),'upic-field-busy.png')});
await waitBurst(false);assert.equal(Number((await state()).density),0,'The event must clear after its brief lifetime');
await page.waitForTimeout(250);await page.evaluate(()=>fixture.event('trade-1'));await page.waitForTimeout(80);assert.equal((await state()).burst,'false','A repeated trade must not flash again');
await page.evaluate(()=>fixture.event('trade-2'));await waitBurst(true);await page.evaluate(()=>fixture.set('paused'));await waitBurst(false);const frozen=await page.locator('canvas').evaluate(c=>({image:c.toDataURL(),phase:c.dataset.phase}));await page.waitForTimeout(300);assert.deepEqual(await page.locator('canvas').evaluate(c=>({image:c.toDataURL(),phase:c.dataset.phase})),frozen,'Pause must clear the event and leave the idle field still');
await page.evaluate(()=>fixture.set('quiet'));await page.waitForTimeout(250);const quiet=await state();assert.equal(quiet.burst,'false');assert.equal(Number(quiet.density),0);await page.screenshot({path:path.join(tmpdir(),'upic-field-quiet.png')});
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>fixture.set('busy'));await page.waitForTimeout(150);const mobile=await page.locator('canvas').evaluate(c=>({width:c.getBoundingClientRect().width,height:c.getBoundingClientRect().height,active:c.dataset.active}));assert.ok(mobile.width>300&&mobile.height>250);assert.equal(mobile.active,'true');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>fixture.event('trade-mobile'));await waitBurst(true);await page.screenshot({path:path.join(tmpdir(),'upic-field-mobile.png')});
await page.evaluate(()=>fixture.seek(12));await waitBurst(false);assert.equal(Number((await state()).density),0,'Seeking establishes a baseline without an event');
await page.evaluate(()=>fixture.replay(13));await waitBurst(true);const replayPhase=(await state()).phase;await waitBurst(false);
await page.evaluate(()=>fixture.seek(12));await waitBurst(false);await page.evaluate(()=>fixture.replay(13));await waitBurst(true);assert.equal((await state()).phase,replayPhase,'Replaying the same candle must reproduce its event geometry');await waitBurst(false);
await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>{fixture.seek(40);fixture.replay(41);});await waitBurst(true);const phase=(await state()).phase;await waitBurst(false);await page.waitForTimeout(250);const reduced=await state();assert.equal(reduced.phase,phase);assert.equal(Number(reduced.density),0,'Reduced motion must still clear finished events');assert.deepEqual(errors,[]);console.log(JSON.stringify({busy,quiet,mobile,errors,eventOnly:true,pausedCleared:true,reducedMotion:true},null,2));}finally{await browser?.close();server.close();}
